### ISSUE TITLE
array_merge_recursive() does not accept unknown named parameters

### ISSUE THREAD

**Issue by CJS-Design** [backdrop-contrib/field_permissions#12]
It is a new installation (brandnew) with few modules (mainly [profiles](https://backdropcms.org/project/profile)). As soon as I try to edit a field in profiles this message appears (and I cannot edit the field):

`ArgumentCountError: array_merge_recursive() does not accept unknown named parameters in array_merge_recursive() (line 233 of /www/htdocs/w01bd48a/backdrop/installation/modules/field_permissions/field_permissions.admin.inc).`

**Comment by CJS-Design** [comment]
This might be because of PHP8?

This is the original line 233:
`$all_assigned_permissions = call_user_func_array('array_merge_recursive', $role_permissions);`

This is the changed line (and it seems to work now):
`$all_assigned_permissions = call_user_func_array('array_merge_recursive', array_values($role_permissions));`

Should this module be PHP8 ready? Or should I put the project on php7?

**Comment by bugfolder** [comment]
Hi @CJS-Design, sorry for the delay; I missed seeing this when you posted it.

You're quite right about the solution. Field Permissions module hasn't been tested for PHP 8 compliance, and so [this issue happens](https://stackoverflow.com/questions/69424097/uncaught-argumentcounterror-array-merge-does-not-accept-unknown-named-paramet). I'll update the module with this fix. Thanks for catching it!

**Comment by CJS-Design** [comment]
Thank you.
