### ISSUE TITLE
Incorrect link URL to Permissions page

### ISSUE THREAD

**Issue by ghost** [backdrop-contrib/field_permissions#16]
On `admin/reports/fields/permissions`, the red 'x's are supposed to link to the Permissions page, but the URL is wrong, so this doesn't work.

The URL is currently: `/admin/people/permissions?destination=admin/reports/fields/permissions#...`

Is should instead be: `/admin/config/people/permissions?destination=admin/reports/fields/permissions#...`

**Comment by bugfolder** [comment]
Thanks, fixed in dev version.
