### ISSUE TITLE
Allow non-authorised users to see the disabled field

### ISSUE THREAD

**Issue by ghost** [backdrop-contrib/field_permissions#17]
Currently it seems that if you don't allow a given role to add/edit values for a field in a content type they otherwise have access to, the field isn't displayed at all. I wonder if we can add an option that allows the field to still be displayed, but disabled (so they can't change it). That'll allow them to see that there's a field there, and what the default/current value is, but still preserve the access controls...

**Comment by yorkshire-pudding** [comment]
+1 vote
I think this is a good idea too

**Comment by nattywebdev** [comment]
This would be an excellent enhancement. I'm currently struggling to set a field that is set with 'view' permission for a particular role (but not edit) such that a user with that role can  see the field value but not edit it. (I've been looking into field_readonly, which I used for this reason in Drupal 7).
I don't really understand why you can set a 'view' permission for a field but not thereby granting the user the ability to  view the field value.
Please consider this enhancement!

**Comment by keiserjb** [comment]
I'm not sure but maybe this patch over on the Drupal module would help.

https://www.drupal.org/project/field_permissions/issues/1547172

**Comment by bugfolder** [comment]
> Please consider this enhancement!

Sounds good to me, too. I'm a bit tied up now, but would welcome a PR (e.g., adapted from the Drupal patch).

**Comment by bugfolder** [comment]
Looks like the newly ported [Field Readonly](https://backdropcms.org/project/field_readonly) module now provides this. I'll update the README for this module to point it out.
