### ISSUE TITLE
Failed to install one project.

### ISSUE THREAD

**Issue by bd0bd** [backdrop-contrib/field_permissions#3]
_Installing projects
100%
Installed 1 out of 1.
Error installing Field Permissions. Cannot extract temporary://update-cache-f4baee9c/1.x-1.0.1, not a valid archive._

_Failed to install one project._

BD 1.4.2

**Comment by olafgrabienski** [comment]
The reason of the error could be a missing `type = module` in `tests/field_permissions.tests.info`.

**Comment by klonos** [comment]
This line has been added to the module for some time now, and is included in the latest version of the module. ...I just tried installing it in a demo site, and I had absolutely no issue.

Closing this one, but please feel free to reopen if this is still happening.

**Comment by olafgrabienski** [comment]
> This line has been added to the module for some time now, and is included in the latest version of the module.

Hm, I don't see the line here: https://github.com/backdrop-contrib/field_permissions/blob/1.x/tests/field_permissions.tests.info. Did I miss something?
