### ISSUE TITLE
[UX] [DX] Module 'Fields permissions' and 'Seven' theme needs work...  'Add content' admin Permissions tab not responsive.

### ISSUE THREAD

**Issue by albanycomputers** [backdrop-contrib/field_permissions#6]
Permissions Tab is not responsive when a large number of Roles exist.

To reproduce the behavior:
1. Make sure there are a few Roles enabled.
2. Go to 'Content'... and 'add content'.
2. Scroll down to 'Permissions' tab.

![image](https://user-images.githubusercontent.com/1705388/143589850-59efeecb-3541-4040-b2ff-d901aa9eef71.png)

**Comment by albanycomputers** [comment]
Actually not sure if this is a module problem or the admin theme problem.

**Comment by bugfolder** [comment]
Actually, this is an issue for Backdrop core; it happens even when the Field Permissions module is disabled. Closing this issue and posting a new one in backdrop/backdrop-issues: https://github.com/backdrop/backdrop-issues/issues/5384
